title: gg
author: shit
email: 1233.com
description: > # this means to ignore newlines until "baseurl:"
  haha.

# social links
twitter_username: holy # DO NOT include the @ character, or else the build will fail!
github_username:  shit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
